baseURL = 'https://knowwvana.github.io/SavitryGreen.T15.Residents/'
languageCode = 'en-us'
title = 'Savitry Greens - Tower 15 Residents'
theme = [] # Crucial: We are NOT using a theme, we are building custom layouts.
publishDir = "docs"
[params]
  secretary_initials = "AG"
  API_URL = "https://script.google.com/macros/s/AKfycbziHRwfhgzg7GgW5mf0riwmknB3T8vZTTgyLogclyxJhfaeZH_tc1Wg-tyRs53mNrhsGg/exec"
